-- ============================================================
--  성장 그래프 — 점수 이력 테이블 (1회 실행)
--  Supabase 대시보드 → SQL Editor 에 붙여넣고 RUN
--
--  ※ scores 테이블은 "유저별 최고점 1행"만 유지(upsert)해서 성장 과정이
--    남지 않음. 이 테이블은 "매 판 1행"을 누적 저장해 성장곡선을 그림.
--  ※ 이 SQL 없이도 성장 그래프는 localStorage 로 동작(같은 기기 한정).
--    실행하면 "기기간 동기화 + 영구 보관"이 켜짐.
--    정책은 기존 scores/wrong_answers 와 동일하게 anon(publishable 키)에 부여.
--
--  재실행 주의: create policy 는 이미 있으면 에러. (정책 줄은 한 번만)
--
--  ★ 2026-07 대체: 이 파일 대신 supabase_security_migration.sql 을 실행할 것.
--    그 파일이 이 테이블 생성을 포함하고(멱등), 아래 anon_delete_history 의
--    무조건 DELETE 허용(USING true) 문제를 문장 단위 대량 삭제 가드 트리거로
--    바로잡는다. 이 파일만 단독 실행하면 가드 없는 정책이 다시 생기니 주의.
-- ============================================================

create table if not exists public.score_history (
  id         bigint generated by default as identity primary key,
  user_name  text not null,
  group_id   text,
  game_id    text not null,
  score      integer not null default 0,
  grade      text,
  combo      integer default 0,
  correct    integer default 0,
  played_at  timestamptz not null default now()
);

create index if not exists score_history_user_idx  on public.score_history (user_name);
create index if not exists score_history_game_idx  on public.score_history (user_name, game_id);
create index if not exists score_history_group_idx on public.score_history (group_id);

-- RLS: 익명 키로 insert/select/delete 허용 (scores·wrong_answers 와 동일 정책)
alter table public.score_history enable row level security;

create policy "anon_insert_history" on public.score_history for insert to anon with check (true);
create policy "anon_select_history" on public.score_history for select to anon using (true);
create policy "anon_delete_history" on public.score_history for delete to anon using (true);
