-- ============================================================
--  supabase_security_migration.sql — 보안·데이터 정합 마이그레이션 (1회 실행)
--  Supabase 대시보드 → SQL Editor 에 "전체"를 붙여넣고 RUN (재실행 안전/멱등)
--
--  ※ 기존 scores / groups 테이블이 이미 있는 라이브 프로젝트
--    (pjagaulfivafamhhiveg) 기준으로 작성됨.
--
--  고치는 문제:
--   [A] wrong_answers·score_history 테이블 미생성
--       → 오답노트/성장 이력의 서버 동기화(wrongnote.js/growth.js)가 전부
--         무음 실패. wrong_answers.sql 의 '적용 완료: 2026-06-24' 주석과 달리
--         실제 DB에는 두 테이블이 없음 → 여기서 생성.
--   [B] scores/groups 의 anon DELETE 정책이 USING(true)
--       → 클라이언트에 노출된 publishable 키만으로 전체 점수·그룹 영구 삭제
--         가능 → 정책 제거 + 비밀번호 검증 RPC(delete_group)로 대체.
--       scores 의 무조건 UPDATE 정책도 제거하고 rename_player RPC 로 대체.
--   [C] groups.teacher_pass 평문 저장 + SELECT 전체 허용
--       → 교수자 비밀번호 전면 노출. 별도 group_secrets 테이블에 bcrypt
--         해시로 분리 저장하고, teacher_pass 컬럼은 조회 차단 + 값 비움.
--         검증은 SECURITY DEFINER RPC(verify_group_pass)로만 수행.
--   [D] 그룹 삭제 후 학생 기기에 남은 hub_group_id 로 upsert_score 호출 시
--       FK(scores_group_id_fkey) 위반으로 점수 저장이 "거짓 성공"으로 유실
--       → FK 를 ON DELETE SET NULL 로 바꾸고, 존재하지 않는 group_id 는
--         트리거로 NULL 처리해 저장 자체는 성공하게 함.
--   [E] score_history.sql:35 / wrong_answers.sql:37 의
--       anon DELETE USING(true) 정책 교정
--       → wrongnote.js/growth.js 가 user_name 필터로 직접 delete 하는 것은
--         유지하되(비로그인 앱이라 행 소유자 식별 불가), 문장 단위 대량 삭제
--         가드 트리거로 테이블 전체 삭제(자명한 필터 공격)를 차단.
--
--  클라이언트(admin.html / group.html / index.html)는 아래 RPC 를 우선
--  호출하고, 이 마이그레이션이 아직 적용되지 않은 DB(RPC 없음, PGRST202)면
--  기존 방식으로 폴백하므로 적용 전·후 모두 동작한다.
-- ============================================================

-- bcrypt 해시용 pgcrypto — Supabase 는 extensions 스키마에 설치돼 있음
create extension if not exists pgcrypto with schema extensions;

set search_path = public, extensions;

-- ────────────────────────────────────────────────────────────
-- [A] 누락 테이블 생성 — wrong_answers(오답노트), score_history(성장 이력)
--     (레포의 wrong_answers.sql / score_history.sql 내용을 통합, 멱등)
-- ────────────────────────────────────────────────────────────
create table if not exists public.wrong_answers (
  id          bigint generated by default as identity primary key,
  user_name   text not null,
  group_id    text,
  game_id     text not null,
  q_key       text not null,
  q_text      text,
  correct     text,
  wrong       text,
  q_type      text,
  created_at  timestamptz not null default now()
);

create index if not exists wrong_answers_user_idx  on public.wrong_answers (user_name);
create index if not exists wrong_answers_group_idx on public.wrong_answers (group_id);

alter table public.wrong_answers enable row level security;

drop policy if exists "anon_insert_wrong" on public.wrong_answers;
drop policy if exists "anon_select_wrong" on public.wrong_answers;
drop policy if exists "anon_delete_wrong" on public.wrong_answers;

create policy "anon_insert_wrong" on public.wrong_answers for insert to anon with check (true);
create policy "anon_select_wrong" on public.wrong_answers for select to anon using (true);
-- delete: wrongnote.js(resolve/clearAll/rename)가 user_name 필터로 직접
-- delete 해야 하므로 정책은 허용하되, 아래 [E]의 대량 삭제 가드로 보호.
create policy "anon_delete_wrong" on public.wrong_answers for delete to anon using (true);

create table if not exists public.score_history (
  id         bigint generated by default as identity primary key,
  user_name  text not null,
  group_id   text,
  game_id    text not null,
  score      integer not null default 0,
  grade      text,
  combo      integer default 0,
  correct    integer default 0,
  played_at  timestamptz not null default now()
);

create index if not exists score_history_user_idx  on public.score_history (user_name);
create index if not exists score_history_game_idx  on public.score_history (user_name, game_id);
create index if not exists score_history_group_idx on public.score_history (group_id);

alter table public.score_history enable row level security;

drop policy if exists "anon_insert_history" on public.score_history;
drop policy if exists "anon_select_history" on public.score_history;
drop policy if exists "anon_delete_history" on public.score_history;

create policy "anon_insert_history" on public.score_history for insert to anon with check (true);
create policy "anon_select_history" on public.score_history for select to anon using (true);
-- delete: growth.js(rename)가 user_name 필터로 직접 delete 해야 하므로
-- 정책은 허용하되, 아래 [E]의 대량 삭제 가드로 보호.
-- (score_history.sql:35 의 무조건 anon_delete_history 정책을 이 조합으로 교정)
create policy "anon_delete_history" on public.score_history for delete to anon using (true);

-- ────────────────────────────────────────────────────────────
-- [E] 대량 삭제 가드 — 한 DELETE 문이 지우는 행 수 상한
--     비로그인(anon 단일 키) 구조라 RLS 로 "자기 행"을 식별할 수 없음.
--     wrongnote.js/growth.js 의 정상 삭제(한 유저 분량)는 통과시키고,
--     자명한 필터(?id=gte.0 등)로 테이블 전체를 지우는 공격을 차단한다.
-- ────────────────────────────────────────────────────────────
create or replace function public.guard_bulk_delete()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_limit bigint := coalesce(nullif(tg_argv[0], '')::bigint, 500);
  v_n     bigint;
begin
  select count(*) into v_n from deleted_rows;
  if v_n > v_limit then
    raise exception 'bulk delete blocked on %: % rows (limit %)', tg_table_name, v_n, v_limit
      using errcode = 'P0001';
  end if;
  return null;
end;
$$;

drop trigger if exists trg_wrong_answers_bulk_guard on public.wrong_answers;
create trigger trg_wrong_answers_bulk_guard
  after delete on public.wrong_answers
  referencing old table as deleted_rows
  for each statement execute function public.guard_bulk_delete('1000');

drop trigger if exists trg_score_history_bulk_guard on public.score_history;
create trigger trg_score_history_bulk_guard
  after delete on public.score_history
  referencing old table as deleted_rows
  for each statement execute function public.guard_bulk_delete('2000');

-- ────────────────────────────────────────────────────────────
-- [C] teacher_pass 분리 — group_secrets(bcrypt 해시) + 컬럼 조회 차단
-- ────────────────────────────────────────────────────────────
create table if not exists public.group_secrets (
  group_id   text primary key references public.groups(id) on delete cascade,
  pass_hash  text not null,
  updated_at timestamptz not null default now()
);

-- RLS 활성 + 정책 없음 + 권한 회수 = API(anon/authenticated) 접근 전면 차단.
-- 접근은 아래 SECURITY DEFINER RPC 로만 이뤄진다.
alter table public.group_secrets enable row level security;
revoke all on table public.group_secrets from anon, authenticated;

-- 기존 평문 비밀번호 → bcrypt 해시로 이전 (이미 이전된 행은 건너뜀)
insert into public.group_secrets (group_id, pass_hash)
select id, extensions.crypt(teacher_pass, extensions.gen_salt('bf'))
from public.groups
where coalesce(teacher_pass, '') <> ''
on conflict (group_id) do nothing;

-- 평문 제거 (컬럼 자체는 구버전 클라이언트 insert 호환을 위해 유지, 값만 비움)
update public.groups set teacher_pass = '' where coalesce(teacher_pass, '') <> '';

-- teacher_pass 컬럼 조회 차단 (컬럼 단위 권한).
-- 클라이언트는 모두 명시적 컬럼 목록(id,name,teacher_name,member_count,created_at)만
-- select 하므로 아래 grant 로 기존 조회는 그대로 동작한다.
revoke select on table public.groups from anon, authenticated;
grant select (id, name, teacher_name, created_at, member_count)
  on table public.groups to anon, authenticated;

-- ────────────────────────────────────────────────────────────
-- RPC ① verify_group_pass(gid, pass) → boolean
--   대시보드 비밀번호 검증. 해시 우선, 구버전 평문이 남아 있으면
--   검증 후 즉시 해시로 승격(lazy upgrade)하고 평문을 지운다.
-- ────────────────────────────────────────────────────────────
create or replace function public.verify_group_pass(p_group_id text, p_pass text)
returns boolean
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_hash  text;
  v_plain text;
begin
  if p_group_id is null or coalesce(p_pass, '') = '' then
    return false;
  end if;

  select pass_hash into v_hash from public.group_secrets where group_id = p_group_id;
  if v_hash is not null then
    return v_hash = crypt(p_pass, v_hash);
  end if;

  -- 레거시 폴백: 구버전 클라이언트가 만든 그룹(평문이 groups 에 남음)
  select teacher_pass into v_plain from public.groups where id = p_group_id;
  if coalesce(v_plain, '') = '' then
    return false;
  end if;
  if v_plain = p_pass then
    insert into public.group_secrets (group_id, pass_hash)
    values (p_group_id, crypt(p_pass, gen_salt('bf')))
    on conflict (group_id) do update
      set pass_hash = excluded.pass_hash, updated_at = now();
    update public.groups set teacher_pass = '' where id = p_group_id;
    return true;
  end if;
  return false;
end;
$$;

revoke all on function public.verify_group_pass(text, text) from public;
grant execute on function public.verify_group_pass(text, text) to anon, authenticated, service_role;

-- ────────────────────────────────────────────────────────────
-- RPC ② create_group(id, name, teacher_name, pass)
--   그룹 생성 + 비밀번호는 group_secrets 에 해시로만 저장(평문 저장 금지).
--   코드 중복이면 unique_violation(23505)을 그대로 던져
--   클라이언트의 기존 재시도 처리(error.code === '23505')와 호환된다.
-- ────────────────────────────────────────────────────────────
create or replace function public.create_group(
  p_id text, p_name text, p_teacher_name text, p_pass text
)
returns void
language plpgsql
security definer
set search_path = public, extensions
as $$
begin
  if p_id is null or p_id !~ '^[A-Z0-9]{6}$' then
    raise exception 'invalid group code' using errcode = '22023';
  end if;
  if length(trim(coalesce(p_name, ''))) < 2 or length(trim(p_name)) > 40 then
    raise exception 'invalid group name' using errcode = '22023';
  end if;
  if length(coalesce(p_pass, '')) < 4 then
    raise exception 'password too short' using errcode = '22023';
  end if;

  insert into public.groups (id, name, teacher_name, member_count, teacher_pass)
  values (p_id, trim(p_name), nullif(trim(coalesce(p_teacher_name, '')), ''), 0, '');

  insert into public.group_secrets (group_id, pass_hash)
  values (p_id, crypt(p_pass, gen_salt('bf')));
end;
$$;

revoke all on function public.create_group(text, text, text, text) from public;
grant execute on function public.create_group(text, text, text, text) to anon, authenticated, service_role;

-- ────────────────────────────────────────────────────────────
-- RPC ③ delete_group(gid, pass) → boolean
--   비밀번호가 맞을 때만 그룹 점수 + 그룹을 삭제(기존 deleteGroup 동작 유지).
--   group_secrets 행은 FK on delete cascade 로 함께 삭제된다.
--   비밀번호 불일치/그룹 없음 → false 반환(아무것도 삭제 안 함).
-- ────────────────────────────────────────────────────────────
create or replace function public.delete_group(p_group_id text, p_pass text)
returns boolean
language plpgsql
security definer
set search_path = public, extensions
as $$
begin
  if not public.verify_group_pass(p_group_id, p_pass) then
    return false;
  end if;
  delete from public.scores where group_id = p_group_id;
  delete from public.groups where id = p_group_id;
  return true;
end;
$$;

revoke all on function public.delete_group(text, text) from public;
grant execute on function public.delete_group(text, text) to anon, authenticated, service_role;

-- ────────────────────────────────────────────────────────────
-- RPC ④ rename_player(old, new) → boolean
--   scores 의 무조건 UPDATE 정책 제거([B])에 대한 대체.
--   새 이름이 이미 존재하면 병합(동명이인 점수 흡수)을 막기 위해 거부.
-- ────────────────────────────────────────────────────────────
create or replace function public.rename_player(p_old text, p_new text)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
  p_old := trim(coalesce(p_old, ''));
  p_new := trim(coalesce(p_new, ''));
  if p_old = '' or p_new = '' or p_old = p_new then
    return false;
  end if;
  if char_length(p_new) < 2 or char_length(p_new) > 30 then
    return false;
  end if;
  if exists (select 1 from public.scores where name = p_new) then
    return false;
  end if;
  update public.scores set name = p_new where name = p_old;
  return true;
end;
$$;

revoke all on function public.rename_player(text, text) from public;
grant execute on function public.rename_player(text, text) to anon, authenticated, service_role;

-- ────────────────────────────────────────────────────────────
-- [B] 위험 정책 제거 — anon 전면 DELETE(USING true) / scores 무조건 UPDATE
--     삭제는 delete_group RPC, 닉네임 변경은 rename_player RPC 로만.
--     (upsert_score 등 SECURITY DEFINER 함수는 소유자 권한으로 실행되므로
--      아래 revoke 의 영향을 받지 않는다)
-- ────────────────────────────────────────────────────────────
drop policy if exists "anon_delete_scores" on public.scores;
drop policy if exists "anon_delete_groups" on public.groups;
revoke delete on table public.scores from anon, authenticated;
revoke delete on table public.groups from anon, authenticated;

drop policy if exists "점수 업데이트 허용" on public.scores;
revoke update on table public.scores from anon, authenticated;

-- ────────────────────────────────────────────────────────────
-- [D] 삭제된 그룹 코드로 인한 점수 저장 실패(FK 위반) 방지
--     1) FK 를 ON DELETE SET NULL 로 — 그룹 삭제 시 남은 점수행은 무소속으로
--     2) BEFORE 트리거 — 존재하지 않는 group_id 로 insert/update 되면
--        NULL 로 바꿔 upsert_score 가 실패하지 않게 함
--        (학생 기기의 hub_group_id 잔존 케이스; 클라이언트도 index.html /
--         group.html 에서 삭제된 그룹을 감지해 localStorage 를 정리한다)
-- ────────────────────────────────────────────────────────────
alter table public.scores drop constraint if exists scores_group_id_fkey;
alter table public.scores
  add constraint scores_group_id_fkey
  foreign key (group_id) references public.groups(id) on delete set null;

create or replace function public.scores_clean_group_id()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.group_id is not null
     and not exists (select 1 from public.groups where id = new.group_id) then
    new.group_id := null;
  end if;
  return new;
end;
$$;

drop trigger if exists trg_scores_clean_group_id on public.scores;
create trigger trg_scores_clean_group_id
  before insert or update on public.scores
  for each row execute function public.scores_clean_group_id();
