-- ============================================================
--  영구 오답노트 — Supabase 테이블 (1회 실행 / 적용 완료: 2026-06-24)
--  Supabase 대시보드 → SQL Editor 에 붙여넣고 RUN
--
--  ※ 이 SQL 없이도 오답노트는 localStorage 로 동작합니다.
--    실행하면 "유저별 서버 영구 저장 + 기기간 동기화"가 켜집니다.
--    정책은 기존 groups/scores 와 동일하게 anon(publishable 키)에 부여.
--    (교실용 앱 보안 수준에 맞춤)
--
--  재실행 주의: create table/index 는 if not exists 라 안전하지만,
--  create policy 는 이미 있으면 에러납니다. 정책 줄은 한 번만 실행.
--  (다시 돌려야 하면 각 policy 앞에
--   drop policy if exists "이름" on public.wrong_answers; 를 추가)
-- ============================================================

create table if not exists public.wrong_answers (
  id          bigint generated by default as identity primary key,
  user_name   text not null,
  group_id    text,
  game_id     text not null,
  q_key       text not null,
  q_text      text,
  correct     text,
  wrong       text,
  q_type      text,
  created_at  timestamptz not null default now()
);

create index if not exists wrong_answers_user_idx  on public.wrong_answers (user_name);
create index if not exists wrong_answers_group_idx on public.wrong_answers (group_id);

-- RLS: 익명 키로 insert/select/delete 허용 (scores 테이블과 동일 정책)
alter table public.wrong_answers enable row level security;

create policy "anon_insert_wrong" on public.wrong_answers for insert to anon with check (true);
create policy "anon_select_wrong" on public.wrong_answers for select to anon using (true);
create policy "anon_delete_wrong" on public.wrong_answers for delete to anon using (true);
